hmLoadTopic({
hmKeywords:"",
hmTitle:"Configuration",
hmDescription:"FlexxLink is installed with a set of default parameters. However, to use the module it is necessary to add configuration for each document, interface, integration party and...",
hmPrevLink:"navigation-and-menu-elements.html",
hmNextLink:"sales-processing.html",
hmParentLink:"user-manual.html",
hmBreadCrumbs:"FlexxLink &gt; <a href=\"user-manual.html\">User manual<\/a>",
hmTitlePath:"FlexxLink > User manual > Configuration",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Configuration<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">FlexxLink is installed with a set of default parameters. However, to use the module it is necessary to add configuration for each document, interface, integration party and validation profile. A valid license key is needed to complete the configuration. Please contact Soluvine GmbH to obtain a license key.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">FlexxLink configuration should be performed in the following order:<\/p>\n\r<p class=\"p_Normal\">1. Refresh interfaces.<\/p>\n\r<p class=\"p_Normal\">2. Configure interfaces:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0.6250rem 0 0 0.8125rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Configure Communication type (synchronous or asynchronous)<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0.6250rem 0 0 0.8125rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>[for asynchronous interfaces] Set up a batch job to process jobs from the interfaces<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0.6250rem 0 0 0.8125rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>NOTE: If Lasernet connector is used, Lasernet reports need to be deployed and configured for Outbound interfaces.<\/p>\n\r<p class=\"p_Normal\">3. Set up Validation rules.<\/p>\n\r<p class=\"p_Normal\">4. Set up Validation profiles.<\/p>\n\r<p class=\"p_Normal\">5. Set up Origins.<\/p>\n\r<p class=\"p_Normal\">6. Set up Parameters and add license key.<\/p>\n\r<p class=\"p_Normal\">7. Set up Rejection codes.<\/p>\n\r<p class=\"p_Normal\">8. Set up Endpoints.<\/p>\n\r<p class=\"p_Normal\">9. Set up Integration party.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
