hmLoadTopic({
hmKeywords:"",
hmTitle:"Integration application",
hmDescription:"Integration applications represent a logical pooling of different interfaces. ",
hmPrevLink:"integration-party2.html",
hmNextLink:"rejection-code2.html",
hmParentLink:"user-manual.html",
hmBreadCrumbs:"FlexxLink &gt; <a href=\"user-manual.html\">User manual<\/a> &gt; Setup",
hmTitlePath:"FlexxLink > User manual > Setup > Integration application",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Integration application<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Integration applications represent a logical pooling of different interfaces. <\/p>\n\r<p class=\"p_Normal\">Integration applications may be of three different types:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>B2B - Application<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Production - Application<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Custom - Application<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Based on the type of application, different settings and parameters can be controlled:<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">B2B - Application<\/span><\/p>\n\r<p class=\"p_Normal\">On an application level, default validation profiles can be assigned for B2B inbound data validation. The selected validation profile is fetched based on the assignment of the integration application on integration party level.<br \/>\n\rThe B2B application can be set to an active \/ inactive status - if a B2B-application is inactive, all integration parties using this application will be in an inactive state as well. <\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Production \/Custom - Application<\/span><\/p>\n\r<p class=\"p_Normal\">On an application level, default validation profiles can be assigned for inbound data validation and inbound and outbound interfaces can be parametrized. <br \/>\n\rThe application can be set to an active \/ inactive status - if an application is inactive, all assigned interfaces will be in an inactive state. <br \/>\n\r&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Sample setup:<\/p>\n\r<div class=\"p_Normal\"><img alt=\"clip-LukasReiter@SLS-LUKAS-0002\" style=\"width:80%;max-width:1613px;height:auto;border:none\" src=\".\/images\/clip-lukasreiter@sls-lukas-0002.png\"\/><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
