hmLoadTopic({
hmKeywords:"",
hmTitle:"Outbound",
hmDescription:"Outbound documents are sent via Seeburger Web service. XML file generated by LaserNet report connector is attached to the call.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"FlexxStore",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Outbound<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Outbound documents are sent via Seeburger Web service. XML file generated by LaserNet report connector is attached to the call.<\/p>\n\r"
})
