pageinfo = [[1681374434,0,0,0,null],
	[1681374434,0,0,0,null],
	[1683104606,0,0,0,null],
	[1683104120,0,0,0,null],
	[1677569368,0,0,0,null],
	[1677569368,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374864,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374828,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680688982,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680783172,0,0,0,null],
	[1680783246,0,0,0,null],
	[1683027694,0,0,0,null],
	[1681374630,0,0,0,null],
	[1681374516,0,0,0,null],
	[1683102842,0,0,0,null],
	[1681374434,0,0,0,null],
	[1681374800,0,0,0,null],
	[1683102000,0,0,0,null],
	[1680783420,0,0,0,null],
	[1680781916,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1683104146,0,0,0,null],
	[1683101544,0,0,0,null],
	[1680771118,0,0,0,null],
	[1680687872,0,0,0,null],
	[1681374434,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1681395018,0,0,0,null],
	[1681374434,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680783372,0,0,0,null],
	[1683029542,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569368,0,0,0,null],
	[1686912552,0,0,0,null],
	[1683099696,0,0,0,null],
	[1681374800,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680783404,0,0,0,null],
	[1683028814,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1683101028,0,0,0,null],
	[1680782272,0,0,0,null],
	[1681374834,0,0,0,null],
	[1680783098,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374800,0,0,0,null],
	[1683113200,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569368,0,0,0,null],
	[1683027652,0,0,0,null],
	[1680688482,0,0,0,null],
	[1681374800,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680783280,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680688482,0,0,0,null],
	[1683099912,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374838,0,0,0,null],
	[1680783338,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374814,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680781748,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569368,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569368,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680783080,0,0,0,null],
	[1680783018,0,0,0,null],
	[1681374800,0,0,0,null],
	[1681374818,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569368,0,0,0,null],
	[1677569368,0,0,0,null],
	[1677569368,0,0,0,null],
	[1680687580,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1683027928,0,0,0,null],
	[1681374800,0,0,0,null],
	[1680688482,0,0,0,null],
	[1677569368,0,0,0,null],
	[1668071676,0,0,0,null],
	[1681374800,0,0,0,null],
	[1680782082,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680781822,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680781814,0,0,0,null],
	[1680781832,0,0,0,null],
	[1677569068,0,0,0,null],
	[1680781844,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1677569068,0,0,0,null],
	[1681374842,0,0,0,null],
	[1680688482,0,0,0,null],
	[1677569068,0,0,0,null],
	[1681394262,0,0,0,null]];
pagedata = [ ["./add-file.html","Attach file","External document can be manually created by the Attach file function from following locations:","./images/zoomimage.jpg"],
["./add-with-cover-sheet.html","Add with Cover sheet","Scanning server by scanning document with Cover sheet (New cover sheet function) creates External document entry in the Document archive. Internal...","./images/zoomimage.jpg"],
["./archive-viewer.html","Archive Viewer","The archive viewer acts as the central place to view files archived via Dynamics 365 Finance &#38; SCM.","./images/zoomimage.jpg"],
["./attach-file.html","Add file","External documents can also be manually added from the general Archive viewer list or other, predefined locations in Dynamics 365 Finance &#38; SCM.","./images/zoomimage.jpg"],
["./authorization.html","Authorization","EDI Management Inbound communication is based on a REST JSON webservices and is using oAuth 2.0 authorization protocol.","./images/zoomimage.jpg"],
["./authorization_2.html","Authorization","EDI Management Inbound communication is based on a REST JSON webservices and is using oAuth 2.0 authorization protocol.","./images/zoomimage.jpg"],
["./axudocarchive.html","AXUDocArchive","Form - Archived documents (AXUDocArchive) System name Details  AXUDocArchive A new form used to show Document archive entries. Form consists ...","./images/zoomimage.jpg"],
["./axudocarchive2.html","AXUDocArchive","Table - Document archive (AXUDocArchive)  System name Label  Details  AXUDocArchive Validation rules  Table used to store docu...","./images/zoomimage.jpg"],
["./axudocarchivedescription.html","AXUDocArchiveDescription","Form - Document description (AXUDocArchiveDescription)","./images/zoomimage.jpg"],
["./axudocarchivedescription2.html","AXUDocArchiveDescription","Table - Document description (AXUDocArchiveDescription)","./images/zoomimage.jpg"],
["./axudocarchivedialoghelper.html","AXUDocArchiveDialogHelper","Class - AXUDocArchiveDialogHelper  System name Details AXUDocArchiveDialogHelper The AXUDocArchiveDialogHelper class is provides logic for Ne...","./images/zoomimage.jpg"],
["./axudocarchivedialoghelperpde_e.html","AXUDocArchiveDialogHelperPDE_Extension","Class - AXUDocArchiveDialogHelperPDE_Extension  System name Details AXUDocArchiveDialogHelperPDE_Extension Extends functionality of the AXUDo...","./images/zoomimage.jpg"],
["./axudocarchiveformpde_extension.html","AXUDocArchiveFormPDE_Extension","Class - AXUDocArchiveFormPDE_Extension  System name Details AXUDocArchiveFormPDE_Extension Extends functionality of the AXUDocArchive form Ex...","./images/zoomimage.jpg"],
["./axudocarchivehelper.html","AXUDocArchiveHelper","Class - AXUDocArchiveHelper  System name Details AXUDocArchiveHelper Event handlers and tools for Document archive Extends: - Extension of: -...","./images/zoomimage.jpg"],
["./axudocarchivehelperpde.html","AXUDocArchiveHelperPDE","Class - AXUDocArchiveHelperPDE  System name Details AXUDocArchiveHelperPDE Event handlers for Document archive Extends: - Extension of: - Met...","./images/zoomimage.jpg"],
["./axudocarchiveimageannotatorcon.html","AXUDocArchiveImageAnnotatorController","Class - AXUDocArchiveImageAnnotatorController  System name Details AXUDocArchiveImageAnnotatorController Creates a new instance of &#60;c&#62;A...","./images/zoomimage.jpg"],
["./axudocarchiveref.html","AXUDocArchiveRef","Table - Document reference (AXUDocArchiveRef)  System name Label  Details  AXUDocArchiveRef Document reference  The AXUDocArch...","./images/zoomimage.jpg"],
["./axudocarchiverefentity.html","AXUDocArchiveRefEntity","Data entity - Document archive reference (AXUDocArchiveRefEntity)","./images/zoomimage.jpg"],
["./axudocarchiverefstaging.html","AXUDocArchiveRefStaging","Table - Document archive [Staging] (AXUDocArchiveRefStaging)","./images/zoomimage.jpg"],
["./axudocarchiveupdate.html","AXUDocArchiveUpdate","Form - Attach file/Add file (AXUDocArchiveUpdate) System name Details  AXUDocArchiveUpdate A new form used as a dialog when creating new exte...","./images/zoomimage.jpg"],
["./axudocarchive_pdeextension.html","AXUDocArchive.PDEExtension","Form extension - Purchase agreements (AXUDocArchive.PDEExtension)","./images/zoomimage.jpg"],
["./axudoccoversheetreport_custom2.html","AXUDocCoverSheetReport_CustomCodePDE_Extension","Class - AXUDocCoverSheetReport_CustomCodePDE_Extension ","./images/zoomimage.jpg"],
["./axudoccoversheetreport_customc.html","AXUDocCoverSheetReport_CustomCode","Class - AXUDocCoverSheetReport_CustomCode  System name Details AXUDocCoverSheetReport_CustomCode The AXUDocCoverSheetReport_CustomCode class ...","./images/zoomimage.jpg"],
["./axudocinternalfilearchive.html","AXUDocInternalFileArchive","Class - AXUDocInternalFileArchive  System name Details AXUDocInternalFileArchive The AXUDocInternalFileArchive class copies File from LACArch...","./images/zoomimage.jpg"],
["./axudocinternalfilearchivepde_e.html","AXUDocInternalFileArchivePDE_Extension","Class - AXUDocInternalFileArchivePDE_Extension  System name Details AXUDocInternalFileArchivePDE_Extension Extends functionality of the AXUDo...","./images/zoomimage.jpg"],
["./axudocinternaltype.html","AXUDocInternalType","Table - Internal documents (AXUDocInternalType)  System name Label  Details  AXUDocInternalType Internal documents  The AXUDoc...","./images/zoomimage.jpg"],
["./axudocinternaltypepde_extensio.html","AXUDocInternalTypePDE_Extension","Class - AXUDocInternalTypePDE_Extension  System name Details AXUDocInternalTypePDE_Extension Extends functionality of the AXUDocInternalType ...","./images/zoomimage.jpg"],
["./axudocparameters.html","AXUDocParameters","Form - Parameters (AXUDocParameters) System name Details  AXUDocParameters A new form used to show Document archive parameters  Label Pa...","./images/zoomimage.jpg"],
["./axudocparameters2.html","AXUDocParameters","Table - Parameters (AXUDocParameters)  System name Label  Details  AXUDocParameters Parameters  The AXUDocParameters table con...","./images/zoomimage.jpg"],
["./axudocparameters_pdeextension.html","AXUDocParameters.PDEExtension","Table extension - Parameters (AXUDocParameters.PDEExtension)","./images/zoomimage.jpg"],
["./axudropfileconstants.html","AXUDropFileConstants","Class - AXUDropFileConstants  System name Details AXUDropFileConstants The AXUDropFileConstants class is used for constants required for File...","./images/zoomimage.jpg"],
["./axudropfilectrl.html","AXUDropFileCtrl","Class - AXUDropFileCtrl  System name Details AXUDropFileCtrl The AXUDropFileCtrl class is used to build control for the file drag &#38; drop ...","./images/zoomimage.jpg"],
["./axudropfilectrlbuild.html","AXUDropFileCtrlBuild","Class - AXUDropFileCtrlBuild  System name Details AXUDropFileCtrlBuild The AXUDropFileCtrlBuild class is required for the file drag &#38; dro...","./images/zoomimage.jpg"],
["./axudropfilectrldemostrategy.html","AXUDropFileCtrlDemoStrategy","Class - AXUDropFileCtrlDemoStrategy  System name Details AXUDropFileCtrlDemoStrategy The AXUDropFileCtrlDemoStrategy class is required for th...","./images/zoomimage.jpg"],
["./business-processes.html","Business processes","EDI Management solution introduces two new processes to the B2B.1 - Business Processes Seeburger Standard entities.","./images/zoomimage.jpg"],
["./chapter-2.html","FlexxStore","Enter topic text here.","./images/zoomimage.jpg"],
["./class-diagrams.html","FXLIntegrationProcess","&#169; Soluvine GmbH Keyboard Navigation F7 for caret browsing Hold ALT and press letter This Info: ALT+q Page Header: ALT+h Topic Header: ALT+t Topic ...","./images/zoomimage.jpg"],
["./classes.html","Classes","Name Developer description FXLBaseContract Base contract class for web services FXLCommunication Framework class for technical communication imple...","./images/zoomimage.jpg"],
["./classifier-mapping.html","Classifier mapping","In order to correctly detect, categorize and route messages from D365 a EDI Management classifier mapping is used. The name of the EDI Management ...","./images/zoomimage.jpg"],
["./collection-processing.html","Collection processing","This menu provides a summary of Collection interfaces processing. It groups and lists the import jobs by status. Each job can be accessed from the...","./images/zoomimage.jpg"],
["./collection-validation-journal.html","Collection validation journal","Collection validation journal is a dedicated job view that allows to review, edit and validate a document. A journal entry for a specific document...","./images/zoomimage.jpg"],
["./configuration.html","Configuration","FlexxLink is installed with a set of default parameters. However, to use the module it is necessary to add configuration for each document, interf...","./images/zoomimage.jpg"],
["./configuration2.html","Configuration","In order to configure the Autoform DM Connector in D365 F&#38;O the following prerequisite information must be provided: ","./images/zoomimage.jpg"],
["./connections.html","Connections","Document archive&#62; Setup&#62; Lasernet&#62; Connections.  Connection defines the storage type and how the storage is accessed from D365 F&#38;amp...","./images/zoomimage.jpg"],
["./connections2.html","Connections","Connection defines the storage type and how the storage is accessed from D365 Finance &#38; SCM. Connection setup is mandatory for Document Archive.","./images/zoomimage.jpg"],
["./data-entities.html","Data entities","Enter topic text here.","./images/zoomimage.jpg"],
["./dmfstagingexecutionhistoryform.html","DMFStagingExecutionHistoryFormAXUDoc_Extension","Class - DMFStagingExecutionHistoryFormAXUDoc_Extension ","./images/zoomimage.jpg"],
["./document-archive-forms.html","Document archive forms","The visibility of document archive functionalities across Dynamics 365 can be configured in this screen.","./images/zoomimage.jpg"],
["./document-log.html","Document log","Document log provides an overview of two data sources: Integration jobs and Import journal. It is used to get a comprehensive insight into how inb...","./images/zoomimage.jpg"],
["./edi-management.html","EDI Management","Enter topic text here.","./images/zoomimage.jpg"],
["./endpoint.html","Endpoint","Enter topic text here.","./images/zoomimage.jpg"],
["./endpoint2.html","Endpoint","Endpoint configuration enables setup of communication parameters of systems that will receive messages sent from D365 F&#38;O using  FlexxLink.","./images/zoomimage.jpg"],
["./external-documents.html","External documents","External documents are documents that are generated outside of D365 and added through:","./images/zoomimage.jpg"],
["./external-documents2.html","External documents","External document types can be predefined in order to ensure a better structure in the archive viewer. ","./images/zoomimage.jpg"],
["./flexxlink-2012.html","FlexxLink 2012","Enter topic text here.","./images/zoomimage.jpg"],
["./flexxware-documentation.html","FlexxWare Documentation","Welcome to the Documentation for FlexxWare!  FlexxLink  FlexxStore  Flexx Framework","./images/zoomimage.jpg"],
["./forms.html","Forms","Enter topic text here.","./images/zoomimage.jpg"],
["./fxlimportinterface.html","FXLImportInterface","&#169; Soluvine GmbH Keyboard Navigation F7 for caret browsing Hold ALT and press letter This Info: ALT+q Page Header: ALT+h Topic Header: ALT+t Topic ...","./images/zoomimage.jpg"],
["./fxlintegrationevent.html","FXLIntegrationEvent","&#169; Soluvine GmbH Keyboard Navigation F7 for caret browsing Hold ALT and press letter This Info: ALT+q Page Header: ALT+h Topic Header: ALT+t Topic ...","./images/zoomimage.jpg"],
["./fxlinterfacevalidation.html","FXLInterfaceValidation","&#169; Soluvine GmbH Keyboard Navigation F7 for caret browsing Hold ALT and press letter This Info: ALT+q Page Header: ALT+h Topic Header: ALT+t Topic ...","./images/zoomimage.jpg"],
["./general-information.html","General information","Who should use this manual?   This manual is written for FlexxLink and Dynamics 365 Finance &#38; SCM administrators  and users. It prov...","./images/zoomimage.jpg"],
["./general.html","General","Autoform DM Connector for Document archive enables integration between D365 F&#38;O Document Archive module and Autoform DM. The connector uses Au...","./images/zoomimage.jpg"],
["./host-entities.html","Host entities","The setup assumes Seeburger Standard solution is used. ","./images/zoomimage.jpg"],
["./http-client-addresses.html","HTTP Client addresses","HTTP Client addresses configuration identifies each document endpoint that can be sent to D365 API. If there is a new endpoint developed on D365 s...","./images/zoomimage.jpg"],
["./http-client-connections.html","HTTP Client connections","In order to send messages to D365 it is necessary to set up HTTP connections and addresses. The HTTP Client connections define the host address of...","./images/zoomimage.jpg"],
["./http-listener.html","HTTP Listener and authentication","The fist step to establish connectivity between the D365 EDI Management and Seeburger BIS is to create an HTTP Listener in order to receive docume...","./images/zoomimage.jpg"],
["./http-server-partners.html","HTTP Server Partners","Following the HTTP Listener configuration it is necessary to set up HTTP Server Partners to specify the IP-range for inbound D365 EDI Management c...","./images/zoomimage.jpg"],
["./import-journal-posting.html","Import journal posting","This menu enables the setup and execution of a batch job that will try posting the FlexxLink documents in approved status. The execution can be do...","./images/zoomimage.jpg"],
["./import-journal.html","Import journal","Import journal in FlexxLink provides basic information about the document received from one of the inbound interfaces and keeps track of the statu...","./images/zoomimage.jpg"],
["./import-labels.html","OCR Import labels","Import labels workspace allows for creation and printing of Label Cover pages which can be used during OCR scanning of invoices to facilitate impo...","./images/zoomimage.jpg"],
["./inbound.html","Inbound","Inbound documents are received via Web services based on a REST/JSON formats described bellow.","./images/zoomimage.jpg"],
["./inbound_2.html","Inbound","Inbound documents are received via Web services based on a REST/JSON formats described bellow.","./images/zoomimage.jpg"],
["./index.html","Welcome","FlexxWare is a range of add-ons for Dynamics 365 Finance &#38; SCM as well as Dynamics AX 2012 R3. ","./images/zoomimage.jpg"],
["./installation.html","Installation","FlexxStore for Dynamics 365 Finance &#38; SCM has to be imported into Microsoft Dynamics Lifecycle services (LCS) as a deployable package.","./images/zoomimage.jpg"],
["./installation2.html","Installation","The SV Document Archive Autoform for Dynamics 365 FO has to be imported into Microsoft Dynamics Lifecycle services(LCS) as a deployable package.","./images/zoomimage.jpg"],
["./integration-job-processing.html","Integration job processing","This menu enables the setup and execution of a batch job that will import integration jobs into  FlexxLink Workspaces. The execution can be d...","./images/zoomimage.jpg"],
["./integration-jobs.html","Integration jobs","Integration jobs in FlexxLink shows a technical report of all the messages that are sent out or received using interfaces. The list shows detailed...","./images/zoomimage.jpg"],
["./integration-monitor.html","Integration monitor","Integration monitor provides a workspace for monitoring the history of jobs processed by the interfaces and quick access to the configuration of F...","./images/zoomimage.jpg"],
["./integration-party.html","Integration party","Enter topic text here.","./images/zoomimage.jpg"],
["./integration-party2.html","Integration party","Integration party setup defines the inbound and outbound interfaces active for each customer and vendor account. The configuration also allows for...","./images/zoomimage.jpg"],
["./interfaces.html","Interfaces","This menu contains information about the installed EDI Management interfaces. They are grouped into inbound and outbound interfaces depending on w...","./images/zoomimage.jpg"],
["./interfaces2.html","Interfaces","In this menu you can configure inbound and outbound interfaces. Interfaces represent FlexxLink capability to send or receive a specific document. ...","./images/zoomimage.jpg"],
["./internal-documents.html","Internal documents","Internal documents are generated as an outcome of predefined Dynamics 365 report execution. The document archiving client uses a Lasernet integrat...","./images/zoomimage.jpg"],
["./introduction.html","Introduction","FlexxLink is a complete Dynamics 365 Finance and Supply Chain Management (Finance/SCM, formerly known as F&#38;O) framework and module that enable...","./images/zoomimage.jpg"],
["./inventweighttablepde_axudoc.html","InventWeightTablePDE.AXUDoc","Form extension - Weighing (InventWeightTablePDE.AXUDoc)","./images/zoomimage.jpg"],
["./invoice-processing.html","Invoice processing","This workspace provides a summary of Purchase Invoice interfaces processing. It groups and lists the import jobs by status. Each job can be access...","./images/zoomimage.jpg"],
["./lacarchivetableaxudoc_extensio.html","LACArchiveTableAXUDoc_Extension","Class - LACArchiveTableAXUDoc_Extension  System name Details LACArchiveTableAXUDoc_Extension The LACArchiveTableAXUDoc_Extension class provid...","./images/zoomimage.jpg"],
["./lacarchive_extensionaxudoc.html","LACArchive.ExtensionAXUDoc","Table extension - Document archive (LACArchive.ExtensionAXUDoc)","./images/zoomimage.jpg"],
["./lacattachmentfileaxudoc_extens.html","LACAttachmentFileAXUDoc_Extension","Class - LACAttachmentFileAXUDoc_Extension  System name Details LACAttachmentFileAXUDoc_Extension Extends functionality of the LACAttachmentFi...","./images/zoomimage.jpg"],
["./lasernet-document-archive-over.html","User Manual","Welcome to the user manual for FlexxStore! The FlexxStore archiving client is used to connect different third-party archiving solutions to Dynamic...","./images/zoomimage.jpg"],
["./mapdb.html","MapDB","D365 EDI Management client uses BIS MapDB functionality to convert account numbers from different companies configured in D365.","./images/zoomimage.jpg"],
["./mappings.html","Mappings","EDI Management mapping package is shipped in a zip file that can be deployed directly in BIS system.","./images/zoomimage.jpg"],
["./message-header.html","Message header","Each XML document would contain FXLHeader section with some key message information:","./images/zoomimage.jpg"],
["./message-header_2.html","Message header","Each XML document would contain FXLHeader section with some key message information:","./images/zoomimage.jpg"],
["./message.html","Message contract","By default all incoming messages would contain \"message\" type element in the header defining some key parameters.","./images/zoomimage.jpg"],
["./message_2.html","Message contract","By default all incoming messages would contain \"message\" type element in the header defining some key parameters.","./images/zoomimage.jpg"],
["./navigation-and-menu-elements.html","Navigation and menu elements","FlexxLink configuration can be accessed by clicking on FlexxLink entry in the D365 Finance/SCM navigation pane:","./images/zoomimage.jpg"],
["./new-topic.html","New topic","Enter topic text here.","./images/zoomimage.jpg"],
["./numberseqmoduleaxudocarchive.html","NumberSeqModuleAXUDocArchive","Class - NumberSeqModuleAXUDocArchive  System name Details NumberSeqModuleAXUDocArchive The NumberSeqModuleAXUDocArchive class maintains numbe...","./images/zoomimage.jpg"],
["./oauth-endpoints.html","OAuth Endpoints","OAuth endpoint has to be configured before the HTTP Client configuration can be started. The OAuth endpoint will be used on HTTP Client address co...","./images/zoomimage.jpg"],
["./ocr-invoice-processing.html","OCR Invoice processing","This menu provides a summary of OCR Invoice processing interface. It groups and lists the imported documents by status. Each document can be acces...","./images/zoomimage.jpg"],
["./origin.html","Origin","Enter topic text here.","./images/zoomimage.jpg"],
["./origin2.html","Origin","Set up of sources of inbound documents and assignation of validation profiles.","./images/zoomimage.jpg"],
["./outbound.html","Outbound","Outbound documents are sent via Seeburger Web service. XML file generated by LaserNet report connector is attached to the call.","./images/zoomimage.jpg"],
["./outbound_2.html","Outbound","Outbound documents are sent via Seeburger Web service. XML file generated by LaserNet report connector is attached to the call.","./images/zoomimage.jpg"],
["./overview.html","Overview","Enter topic text here.","./images/zoomimage.jpg"],
["./parameters.html","Parameters","Document archive&#62; Setup&#62; Parameters  Document Archive parameters have to be provided to adjust the module settings to the installation ...","./images/zoomimage.jpg"],
["./parameters2.html","Parameters","FlexxLink requires setup of the following parameters.","./images/zoomimage.jpg"],
["./partner-entities.html","Partner entities","Setup of partner entities is outside of the scope of EDI Management solution. The solution supports all types of Customer and Trading Partner setu...","./images/zoomimage.jpg"],
["./pdetraderinboundscreenpostaxud.html","PDETraderInboundScreenPostAXUDoc_Extension","Class - PDETraderInboundScreenPostAXUDoc_Extension ","./images/zoomimage.jpg"],
["./pdetraderinboundscreen_axudoc.html","PDETraderInboundScreen.AXUDoc","Form extension - Trader inbound screen (PDETraderInboundScreen.AXUDoc)","./images/zoomimage.jpg"],
["./pending-vendor-invoices.html","Pending vendor invoices","This workspace is an extension of a default Dynamics 365 Finance &#38; SCM workspace for Pending vendor invoices which displays only documents imp...","./images/zoomimage.jpg"],
["./purchagreementheadertableaxudo.html","PurchAgreementHeaderTableAXUDoc_Extension","Class - PurchAgreementHeaderTableAXUDoc_Extension ","./images/zoomimage.jpg"],
["./purchagreement_axudoc.html","PurchAgreement.AXUDoc","Form extension - Purchase agreements (PurchAgreement.AXUDoc)","./images/zoomimage.jpg"],
["./purchase-confirmation.html","Purchase confirmation","Purchase confirmation send function, executed from Purchase confirmation journal form in D365FO.","./images/zoomimage.jpg"],
["./purchase-confirmation_2.html","Purchase confirmation","Purchase confirmation send function, executed from Purchase confirmation journal form in D365FO.","./images/zoomimage.jpg"],
["./purchase-order-create.html","Purchase order create","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/createPurchTable &#38;n...","./images/zoomimage.jpg"],
["./purchase-order-create_2.html","Purchase order create_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLSalesTableService/createSalesTable &#38;n...","./images/zoomimage.jpg"],
["./purchase-order-create_2_2.html","Purchase order create_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLSalesTableService/createSalesTable &#38;n...","./images/zoomimage.jpg"],
["./purchase-order-create_3.html","Purchase order create_3","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLCustCollectionService/confirmCollecti...","./images/zoomimage.jpg"],
["./purchase-order-create_3_2.html","Purchase order create_3","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLCustCollectionService/confirmCollecti...","./images/zoomimage.jpg"],
["./purchase-order-create_4.html","Purchase order create","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/createPurchTable &#38;n...","./images/zoomimage.jpg"],
["./purchase-order-send.html","Purchase order","Purchase order send function, executed from Purchase orders form in D365FO.","./images/zoomimage.jpg"],
["./purchase-order-send_2.html","Purchase order","Purchase order send function, executed from Purchase orders form in D365FO.","./images/zoomimage.jpg"],
["./purchase-order-validation-jour.html","Purchase order validation journal","Purchase order validation journal is a dedicated job view that allows to review, edit and validate a document. A journal entry for a specific docu...","./images/zoomimage.jpg"],
["./purchase-processing.html","Purchase processing","This menu provides a summary of Purchase interfaces processing. It groups and lists the import jobs by status. Each job can be accessed from the l...","./images/zoomimage.jpg"],
["./purchlinetableaxudocpde_extens.html","PurchLineTableAXUDocPDE_Extension","Class - PurchLineTableAXUDocPDE_Extension  System name Details PurchLineTableAXUDocPDE_Extension Extends functionality of the PurchLine table...","./images/zoomimage.jpg"],
["./purchtable_axudoc.html","PurchTable.AXUDoc","Form extension - Purchase orders (PurchTable.AXUDoc)","./images/zoomimage.jpg"],
["./rejection-code.html","Rejection code","Enter topic text here.","./images/zoomimage.jpg"],
["./rejection-code2.html","Rejection code","Rejection codes are used to define the items in the list used when rejecting a document in the Import journal workspace. ","./images/zoomimage.jpg"],
["./rules.html","Rules","An additional rule need to be set up to enable processing incoming D365 EDI Management client with Seeburger standard solution. ","./images/zoomimage.jpg"],
["./sales-invoice.html","Sales invoice","Sales invoice send function, executed from Sales invoice journal form in AX.","./images/zoomimage.jpg"],
["./sales-invoice_2.html","Sales invoice","Sales invoice send function, executed from Sales invoice journal form in AX.","./images/zoomimage.jpg"],
["./sales-order-confirmation.html","Sales order confirmation","Sales order confirmation send function, executed from Sales order confirmations form in AX.","./images/zoomimage.jpg"],
["./sales-order-confirmation_2.html","Sales order confirmation","Sales order confirmation send function, executed from Sales order confirmations form in AX.","./images/zoomimage.jpg"],
["./sales-order-update.html","Sales order update","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLSalesTableService/updateSalesTable &#38;n...","./images/zoomimage.jpg"],
["./sales-order-update_2.html","Sales order update_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/confirmPurchTable &#38;...","./images/zoomimage.jpg"],
["./sales-order-update_2_2.html","Sales order update_2_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/invoicePurchTable &#38;...","./images/zoomimage.jpg"],
["./sales-order-update_2_2_2.html","Sales order update_2_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/invoicePurchTable &#38;...","./images/zoomimage.jpg"],
["./sales-order-update_2_3.html","Sales order update_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/confirmPurchTable &#38;...","./images/zoomimage.jpg"],
["./sales-order-update_3.html","Sales order update","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLSalesTableService/updateSalesTable &#38;n...","./images/zoomimage.jpg"],
["./sales-order-validation-journal.html","Sales order validation journal","Sales order validation journal is a dedicated job view that allows to review, edit and validate a document. A journal entry for a specific documen...","./images/zoomimage.jpg"],
["./sales-packing-slip.html","Sales packing slip","Sales packing slip send function, executed from Sales packing slip journal form in AX.","./images/zoomimage.jpg"],
["./sales-packing-slip_2.html","Sales packing slip","Sales packing slip send function, executed from Sales packing slip journal form in AX.","./images/zoomimage.jpg"],
["./sales-processing.html","Sales processing","This menu provides a summary of Sales interfaces processing. It groups and lists the import jobs by status. Each job can be accessed from the list...","./images/zoomimage.jpg"],
["./salesagreementheadertableaxudo.html","SalesAgreementHeaderTableAXUDoc_Extension","Class - SalesAgreementHeaderTableAXUDoc_Extension ","./images/zoomimage.jpg"],
["./second-topic.html","Second topic","Enter topic text here.","./images/zoomimage.jpg"],
["./security-configuration.html","Security configuration","FlexxLink is shipped with a predefined set of privileges. The following chapter describes what each privilege refers to and what level of access i...","./images/zoomimage.jpg"],
["./security-configuration_2.html","Security configuration_2","FlexxLink is shipped with a predefined set of privileges. The following chapter describes what each privilege refers to and what level of access i...","./images/zoomimage.jpg"],
["./security-objects2.html","Security objects","Object Type System name Label Access Privileges AXUDocArchiveMaintain Maintain trader documents archive Delete Belongs to Duty: AXUDocArchiveMaint...","./images/zoomimage.jpg"],
["./seeburger-bis.html","Seeburger BIS","Enter topic text here.","./images/zoomimage.jpg"],
["./seexmlmapping.html","SEEXMLMapping","Mapping name: FXL_PurchaseOrder_TO_SEEDELFOR_V3_0  FXL_PurchaseOrder (Source message) Condition SEEDELFOR_V3_0 (Destination message) Report.P...","./images/zoomimage.jpg"],
["./seexmlmapping_2.html","SEEXMLMapping_2","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_2_2.html","SEEXMLMapping_2","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3.html","SEEXMLMapping_3","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3_2.html","SEEXMLMapping_3_2","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3_2_2.html","SEEXMLMapping_3_2","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3_3.html","SEEXMLMapping_3_3","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3_3_2.html","SEEXMLMapping_3_3","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3_4.html","SEEXMLMapping_3","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_4.html","SEEXMLMapping","Mapping name: FXL_PurchaseOrder_TO_SEEDELFOR_V3_0  FXL_PurchaseOrder (Source message) Condition SEEDELFOR_V3_0 (Destination message) Report.P...","./images/zoomimage.jpg"],
["./settlementtablepde_axudoc.html","SettlementTablePDE.AXUDoc","Form extension - Trader inbound screen (SettlementTablePDE.AXUDoc)","./images/zoomimage.jpg"],
["./sub-chapter-2_1.html","Sub chapter 2.1","Enter topic text here.","./images/zoomimage.jpg"],
["./tables.html","Tables","Name Developer description FXLCustCollectionLine The FXLCustCollectionLine table contains imported line data for collection interface. FXLCustColl...","./images/zoomimage.jpg"],
["./terms-of-use.html","Terms of use","No part of this publication may be reproduced, transmitted, transcribed, or translated into any language in any form by any means without the prio...","./images/zoomimage.jpg"]];
